name = "pkx-v1-store"
pages_build_output_dir = "dist"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[placement]
mode = "smart"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "pkx-v1-db"
database_id = "391296c1-bd7b-4649-a810-611487f27582"

# R2 Bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "pkx-v1-images"

[vars]
ENVIRONMENT = "production"
